YONK-16: Added split module store for tests
edx-solutions/gradebook-edx-platform-extensions pull request #15
Opened 2017-06-09 09:37 UTC by aamishbaloch

2017-09-18 14:43 UTC, aamishbaloch commented
@ziafazal Can you review this?

2017-09-20 05:51 UTC, ziafazal requested changes
@aamishbaloch could you please make changes as suggested in comments.

2017-09-20 05:51 UTC, ziafazal commented on gradebook/tests.py
> +            u'location': 'block-v1:{org}+{num}+GRAD1+type@sequential+block@Sequence_2'.format(
`GRAD1` is course run if you can replace that with `course.run` as you did for org and number that would make it more flexible.

2017-09-20 05:51 UTC, ziafazal commented on gradebook/tests.py
> +            u'location': 'block-v1:{org}+{num}+GRAD1+type@sequential+block@Sequence_3'.format(
same here

2017-09-21 07:52 UTC, aamishbaloch commented
@ziafazal Done with the change. Can you review it?

2017-10-09 09:15 UTC, ziafazal approved these changes
LGTM

2017-10-09 09:15 UTC, merged